// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl6K8a6TMR3REU47UQDBI8M0EyBbwxrY4',
    appId: '1:940407937295:web:33753b2b03b5952d03867a',
    messagingSenderId: '940407937295',
    projectId: 'recipe-app-flutter-bd47d',
    authDomain: 'recipe-app-flutter-bd47d.firebaseapp.com',
    databaseURL: 'https://recipe-app-flutter-bd47d-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-flutter-bd47d.firebasestorage.app',
    measurementId: 'G-FX7M9PN0NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZae_9Q_TZCzUt96dx6gkK2m4_jxSkonI',
    appId: '1:940407937295:android:064334a5e934a01a03867a',
    messagingSenderId: '940407937295',
    projectId: 'recipe-app-flutter-bd47d',
    databaseURL: 'https://recipe-app-flutter-bd47d-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-flutter-bd47d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qhFTw0G7cIdwDKIOYg1JUh6_nn6GtBI',
    appId: '1:940407937295:ios:bd34b8d7caaa806003867a',
    messagingSenderId: '940407937295',
    projectId: 'recipe-app-flutter-bd47d',
    databaseURL: 'https://recipe-app-flutter-bd47d-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-flutter-bd47d.firebasestorage.app',
    androidClientId: '940407937295-t42b8rv3jt8ir9886t7j505ddr4aq8b0.apps.googleusercontent.com',
    iosClientId: '940407937295-ajtde4c7hro6d9c98s0ssd4c194arkm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiResep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7qhFTw0G7cIdwDKIOYg1JUh6_nn6GtBI',
    appId: '1:940407937295:ios:bd34b8d7caaa806003867a',
    messagingSenderId: '940407937295',
    projectId: 'recipe-app-flutter-bd47d',
    databaseURL: 'https://recipe-app-flutter-bd47d-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-flutter-bd47d.firebasestorage.app',
    androidClientId: '940407937295-t42b8rv3jt8ir9886t7j505ddr4aq8b0.apps.googleusercontent.com',
    iosClientId: '940407937295-ajtde4c7hro6d9c98s0ssd4c194arkm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiResep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl6K8a6TMR3REU47UQDBI8M0EyBbwxrY4',
    appId: '1:940407937295:web:13405b1624da978f03867a',
    messagingSenderId: '940407937295',
    projectId: 'recipe-app-flutter-bd47d',
    authDomain: 'recipe-app-flutter-bd47d.firebaseapp.com',
    databaseURL: 'https://recipe-app-flutter-bd47d-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-flutter-bd47d.firebasestorage.app',
    measurementId: 'G-56K8FWHGTR',
  );

}